<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Get started with Yii' => 'Comience con Yii',
    'Heading' => 'título',
    'My Yii Application' => 'Mi aplicación Yii',
    'Yii Documentation' => 'Yii Documentación',
    'Yii Extensions' => 'Extensiones Yii',
    'Yii Forum' => 'Yii Foro',
    'Are you sure you want to delete this item?' => '¿Seguro que quieres borrar este artículo?',
    'Congratulations!' => '¡Enhorabuena!',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Created At' => 'Creado el',
    'Delete' => 'Borrar',
    'ID' => 'identificación',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit , sed no tempor eiusmod ut labore et dolore incididunt magna aliqua . Ut enim ad minim veniam , nostrud quis ullamco exercitation nisi ut laboris aliquip commodo ex ea consequat . Duis Aute Irure dolor en reprehenderit en voluptate velita esse cillum dolore eu nulla fugiat pariatur .',
    'Message' => 'Mensaje',
    'Permissions' => 'Permisos',
    'Reset' => 'Reajustar',
    'Search' => 'Búsqueda',
    'Statuses' => 'Los estados',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualización {modelClass} :',
    'Updated At' => 'Actualizado a',
    'You have successfully created your Yii-powered application.' => 'Ha creado su aplicación Yii con alimentación.',
    'Home'=>'Inicio',
    'Create User'=>'Crear usuario',
    'Users'=>'Usuarios',
    'Create Dispositivos'=>'Crear Dispositivos',
    
];

